const Discord = require('discord.js')

exports.run = (bot, message, args) => {
  var jokes = ["Yo mama's so stupid that she bought tickets to Xbox Live.",
  "Yo mama's so stupid that whenever someone rings the doorbell, she checks the microwave.",
  "Yo mama's so stupid that when she broke her VCR, she bought a video tape on how to fix your VCR.",
  "Yo mama is so stupid that she tried to drop acid but the car battery fell on her foot.",
  "Yo mama so dumb, she lost a spelling bee to Hodor",
  "Yo Mama so dumb, she thought Bran Stark was a type of muffin.",
  "Yo mama so fat, she Winter-fell and couldn't get up!",
  "Yo mama so old, the old gods pray to HER!",
  "Yo Mama So Fat, she can't fit through the moon door.",
  "Yo mama so ugly, winter turned around and left!",
  "Yo mama so fat, even Roose Bolton won't touch her",
  "Yo mama so bad at sex, the only kind of head she gives is severed.",
  "Yo mama is so stupid that she wiped her ass before she took a shit.",
  "Yo mama is so stupid that she thinks socialism means partying!",
  "Yo mama is so stupid that she thinks deadbeat is a type of music.",
  "Yo mama is so stupid that she thinks Tiger Woods is a forest.",
  "Yo mama is so stupid that she put two M&M's in her ears and thought she was listening to Eminem.",
  "Yo mama is so stupid that at bottom of application where it says Sign Here - she put Scorpio.",
  "Yo mama is so stupid that she wouldn't know up from down if she had three guesses.",
  "Yo mama is so stupid that she once attempted to commit suicide by jumping off a curb.",
  "Yo mama is so stupid that she put on bug spray before going to the flea market.",
  "Yo mama is so stupid that she stole free bread.",
  "Yo mama is so stupid that she locked her keys inside a motorcycle.",
  "Yo mama's so stupid that she got locked inside a motorcycle.",
  "Yo mama's so stupid that she went to the dentist to get a bluetooth.",
  "Yo mama is so fat that her bellybutton gets home 15 minutes before she does.",
  "Yo mama is so fat that when she was diagnosed with a flesh-eating disease, the doctor gave her ten years to live.",
  "Yo mama is so fat that the National Weather Service names each one of her farts.",
  "Yo mama is so fat that when she wears a yellow raincoat, people yell \"taxi!\"",
  "Yo mama is so fat and dumb that the only reason she opened her email was because she heard it contained spam.",
  "Yo mama is so fat she threw on a sheet for Halloween and went as Antarctica.",
  "Yo mama is so fat that she looked up cheat codes for Wii Fit",
  "Yo mama is so fat that the only exercise she gets is when she chases the ice cream truck.",
  "Yo mama is so fat that she sat on a dollar and squeezed a booger out George Washington's nose.",
  "Yo mama is so fat that when she gets in an elevator, it has to go down.",
  "Yo mama is so fat that when her beeper goes off, people think she's backing up.",
  "Yo mama is so fat that she has to iron her pants on the driveway.",
  "Yo mama is so fat that she left the house in high heels and came back wearing flip flops.",
  "Yo mama is so greasy that she sweats butter and syrup and has a full time job at Denny's wiping pancakes across her forehead.",
  "Yo mama is so greasy that her freckles slipped off.",
  "Yo mama is so greasy that if Crisco had a football team, she'd be the mascot.",
  "Yo mama is so greasy that she squeezes Crisco from her hair to bake cookies.",
  "Yo mama is so greasy that she's labeled as an ingredient in Crisco.",
  "Yo mama is so greasy that you could fry a chicken dinner for 12 on her forehead.",
  "Yo mama is so greasy that I buttered my popcorn with her leg hairs.",
  "Yo mama's house is so dirty that roaches ride around on dune buggies!",
  "Yo mama's house is so dirty that she has to wipe her feet before she goes outside.",
  "Yo mama's teeth are so rotten that when she smiles it looks like she has dice in her mouth.",
  "Yo mama's teeth are so yellow that traffic slows down when she smiles!",
  "Yo mama's teeth are so yellow that she spits butter!",
  "Yo mama's so dirty, she fertilizes her lawn by rolling in it!",
  "Yo mama's so dirty, when a seed gets stuck in her ass crack it beings to grow!",
  "Yo mama's so dirty, she jumped in a river and created a mud slide!",
  "Yo mama's so dirty, when the wind blows people yell \"'Sand storm!!!\'",
  "Yo mama's so greasy, on hot days she cooks bacon strips on her ass cheeks!",
  "Yo mama is so short that her homies are the Keebler Elfs.",
  'Yo mama is so short that she has to get a running start to get up on the toilet.',
  'Yo mama is so short that when she sneezes, she hits her head on the floor.',
  'Yo mama is so short that she does pull-ups on a staple.',
  'Yo mama is so short that she can do push-ups under the door.',
  'Yo mama is so short that when I was dissin\' her she tried to jump kick me in the ankle.',
  'Yo mama is so short that she can limbo under the door.',
  'Yo mama is so short that she uses a condom for a sleeping bag.',
  'Yo mama is so short that she slam-dunks her bus fare.',
  'Yo mama is so short that she has to look up to look down.',
  'Yo mama is so short that she makes Gary Coleman look like Shaquille O\'Neal.',
  'Yo mama is so short, you can make a life size sculpture of her using one can of Play-Doh.',
  'Yo mama\'s so short that when she sat on the curb her feet didn\'t touch the ground.',
  'Yo mama is so short that she can play handball on the curb.',
  'Yo mama has so much hair on her upper lip that she braids it.',
  'Yo mama is so hairy that Bigfoot wants to take HER picture!',
  'Yo mama is so hairy that she looks like she has Buckwheat in a headlock.',
  'Yo mama is so hairy that you almost died of rugburn at birth!',
  'Yo mama is so hairy that they filmed "Gorillas in the Mist" in her shower!',
  'Yo mama is so hairy that if she could fly she\'d look like a magic carpet.',
  'Yo mama is so hairy that she looks like Bigfoot in a tank top.',
  'Yo mama is so hairy that she has afros on her nipples.',
  'Yo mama is so hairy that when I took her to a pet store they locked her in a cage.',
  'Yo mama is so hairy that she looks like a Chia pet with a sweater on.',
  'Yo mama is so hairy that Jane Goodall follows her around.',
  'Yo mama is so hairy that the only language she can speak is wookie.']


  var embed = new Discord.RichEmbed()
  .setDescription(`**__${jokes[Math.floor(Math.random()*jokes.length)]}__**`)
  .setColor("#6b93d6")
  message.channel.send({ embed: embed })
}

exports.help = {
  name: 'yomamma',
  description: 'Gets a random Yo Mama Joke',
  usage: "pr!yomamma",
  note: "May be innapropiate!"
}

